### ISSUE TITLE
Please create a git tag for versioning.

### ISSUE THREAD

**Issue by PertuyF** [LinearFold/LinearPartition#1]
Dear @VincentZhangOR @LinearFold,

Thank you very much for the effort you put into developing LinearPartition. As [proposed for LinearFold](https://github.com/LinearFold/LinearFold/issues/4), I am willing to create a conda package for LinearPartition on Bioconda, that would facilitate distribution. The requirement for this is that you adopt some versioning strategy using a github release or a git tag.
Could you please do so?

Best,
Fabien

**Comment by LinearFold** [comment]
Hello Fabien,

We've released a version with tag "LinearPartition version 1.0". Thanks again for your interest.

Best,
LinearFold Group

**Comment by PertuyF** [comment]
@LinearFold thank you very much!
My PR to Bioconda were merged, linearpartition and linearfold should soon be available as conda packages and biocontainers (docker images).

Please note that I was not able to include some graphical tools (draw_circular and draw_bpp_plot) as the current python wrappers do not allow to relocate the executables through symbolic links. I currently don't have bandwidth to submit PR, buy we can discuss how to fix this if you want.

Best,
Fabien
